### ISSUE TITLE
please make sure ssh:// links can be wired through aminal ssh or mosh client

### ISSUE THREAD

**Issue by cjw296** [liamg/aminal#205]
**Is your feature request related to a problem? Please describe.**

It's really powerful to be able to build links to hosts in environment monitoring web apps. These are often of the form ssh://[user@]host. 

**Describe the solution you'd like**

Have a way, preferably done as part of installation on Windows, to set up url handlers for ssh:// that feed through to Aminal such that it opens a new shell in a new tab and ssh's to the host and optional user specified.

**Describe alternatives you've considered**

Terminal in macOS does this flawlessly out of the box.

Chrome's SSH app does this on Windows, but, annoyingly, specifying the user is mandatory. If unspecified, it should just use the logged in user's username.

**Comment by rrrooommmaaa** [comment]
To register an application for ssh:// please follow the instructions at
https://msdn.microsoft.com/en-us/windows/desktop/aa767914
Here is an example for putty (need to specify the correct path)
[ssh_example.zip](https://github.com/liamg/aminal/files/2971713/ssh_example.zip)
For putty, we can't just use `putty.exe` because it doesn't support a parameter in form of ssh://user@host.
So we need to copy `putty.bat` from here https://gist.github.com/sbiffi/11256316 (it does the parsing and calls correct arguments)
[putty.bat.zip](https://github.com/liamg/aminal/files/2971737/putty.bat.zip)
Note: we need to specify correct path to `putty.exe` inside `putty.bat`
If we need to get current system user and add itas an argument to `putty.exe` the right place to do it is in `putty.bat', I suppose

**Comment by cjw296** [comment]
Okay, so two problems spill out from this:
1. getting a decent SSH client that Aminal likes playing with.
2. Having aminal set this stuff up itself, as part of the installer, or better, as something that gets triggered both on install and by menu it somewhere (re-install url handlers).

(2) is bigger, because we probably want to support installing and managing multiple templated url handlers (ssh://, mosh://, etc)

**Comment by nikitar020** [comment]
For (1), we're going to use OpenSSH which is de-facto standard and is already provided by Windows. For (2) - it is not a problem to have the installer to maintain an arbitrary number of URL handlers, and reinstall them as part of the "repair installation" feature.

**Comment by cjw296** [comment]
"repair" doesn't feel like the the right wording here, "url handling configuration" or some variant seems like the right thing, with a "make the windows registry match what I've set up in aminal"  button

**Comment by mjs** [comment]
Moved to https://github.com/jumptrading/waminal/issues/2
